[package]
name = "pongccheatsd"
version = "1.0.0"
edition = "2021"

[dependencies]
serde_json = "1.0.70"
serde = { version = "1.0.130", features = ["derive"] }
libc = "0.2.107"
nix = "0.23.0"
procfs = "0.11.0"
